name: Mastodon Action
description: Toots the head commit on push

inputs:
  mastodon-url: 
    description: URL of Mastodon instance
    required: true
  message:
    description: Message to display with toot
    default: New commit to repository!

runs:
  using: node12
  main: dist/index.js