name: Main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mastodon notification
        uses: jasmaa/mastodon-action@master
        env:
          TOKEN: ${{ secrets.TOKEN }}
        with:
          mastodon-url: mastodon.social
          message: New commit to mastodon-action!
