name: Main
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mastodon notification
        uses: jasmaa/mastodon-action
        with:
          client-id: test client id
          client-secret: test client secret